# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    untracked: true
    paths:
        - node_modules/
        - dist/
stages:
    - test
    - build
    - publish

test:
    stage: "test"
    image: node:latest
    before_script:
        - npm install -g eslint typescript ts-node
        - npm install
    script:
        - npm test

build:
    stage: "build"
    image: node:latest
    before_script:
        - npm install -g eslint typescript ts-node
        - npm install
    script:
        - npm run prepublish
    # only:
    #     - master

publish:
    stage: "publish"
